### ISSUE TITLE
Remove all Furniture

### ISSUE THREAD

**Issue by pinoylifecraft** [Ste3et/FurnitureLibExemple#1]
[17:07:56 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:46) [craftbukki
t.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:7
26) [craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:3
99) [craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:6
65) [craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java
:564) [craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at com.lenis0012.bukkit.ls.util.LoggingFilter.handle(LoggingFilter.java:
17) ~[?:?]
        at com.lenis0012.bukkit.ls.util.LoggingFilter.filter(LoggingFilter.java:
28) ~[?:?]
        at org.apache.logging.log4j.core.filter.CompositeFilter.filter(Composite
Filter.java:231) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at org.apache.logging.log4j.core.filter.CompositeFilter.filter(Composite
Filter.java:231) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at org.apache.logging.log4j.core.filter.AbstractFilterable.isFiltered(Ab
stractFilterable.java:124) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.ja
va:400) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.ja
va:367) [craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at org.apache.logging.log4j.core.Logger.log(Logger.java:110) [craftbukki
t.jar:git-Spigot-798f32d-0cd0397]
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java
:609) [craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.util.ForwardLogHandler.publish(Forward
LogHandler.java:33) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at java.util.logging.Logger.log(Unknown Source) ~[?:1.8.0_91]
        at java.util.logging.Logger.doLog(Unknown Source) ~[?:1.8.0_91]
        at java.util.logging.Logger.log(Unknown Source) ~[?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerCon
nection.java:1355) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java
:1184) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java
:45) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java
:1) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:1
3) ~[craftbukkit.jar:git-Spigot-798f32d-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~
[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) ~[craftbukk
it.jar:git-Spigot-798f32d-0cd0397]
        ... 5 more

**Comment by Ste3et** [comment]
I see it is a NullPointerException but i cannot see it is a problem with my plugin can you send me your complete latest.log please to fixe it.

**Comment by pinoylifecraft** [comment]
[latest.zip](https://github.com/Ste3et/FurnitureLibExemple/files/332849/latest.zip)
