### ISSUE TITLE
FurnitureLib 1.7.7 Up to date? What?

### ISSUE THREAD

**Issue by pinoylifecraft** [Ste3et/FurnitureLibExemple#2]
[16:12:00 INFO]: [FurnitureLib] Enabling FurnitureLib v1.7.7
[16:12:00 INFO]: **Vault not found**
[16:12:00 INFO]: [FurnitureLib] Disabling FurnitureLib v1.7.7
[16:12:00 INFO]: [FurnitureLib] ==========================================
[16:12:00 INFO]: [FurnitureLib] Furniture shutdown started
[16:12:00 ERROR]: **Error occurred while disabling FurnitureLib v1.7.7 (Is it up t
o date?)**
java.lang.NullPointerException
        at de.Ste3et_C0st.FurnitureLib.main.FurnitureLib.onDisable(FurnitureLib.
java:302) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[c
raftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoade
r.java:361) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManag
er.java:424) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at de.Ste3et_C0st.FurnitureLib.main.FurnitureLib.onEnable(FurnitureLib.j
ava:121) [FurnitureLib.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) [cr
aftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:337) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:405) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.
java:373) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer
.java:323) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:
412) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:
377) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:
332) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.ja
va:271) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:535) [craftbukkit.jar:git-Spigot-570526c-6af9f5b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by pinoylifecraft** [comment]
Also in DiceFurniture!
Error to

**Comment by Ste3et** [comment]
Vault not found install it : https://dev.bukkit.org/bukkit-plugins/vault/

**Comment by pinoylifecraft** [comment]
I already Install it!
It's look like it's not my problem it's your Plugin problem :stuck_out_tongue_winking_eye: Hehe :)

**Comment by Ste3et** [comment]
End where is the plugin log e mean it's 100% a fail from you.

**Comment by pinoylifecraft** [comment]
So what should I do?
I always Update the Plugin and still Out dated :disappointed: I'm always Up to date :gem:

**Comment by Ste3et** [comment]
send me your lastest.log and i can help you

**Comment by Ste3et** [comment]
Fixed please install FurnitureLib 1.7.7.5
